Client course api
cesantos647/2021-fall-cs160-team-loki pull request #32
Opened 2021-11-28 10:55 UTC by HoaiNamPhung

2021-11-28 10:59 UTC, HoaiNamPhung commented
Need some help with retrieving data from a promise without access to lifecycle stuff (like componentDidMount) in order to load user's courses into HTML/CSS. See line 15, 33, and 95 of Navbar.js.

Currently also need to log on/off in order to update props.auth to contain any newly added courses for a user. Will change so that GET is automatically called to update props.auth on course addition/creation later.

2021-11-30 11:55 UTC, HoaiNamPhung commented
> Need some help with retrieving data from a promise without access to lifecycle stuff (like componentDidMount) in order to load user's courses into HTML/CSS. See line 15, 33, and 95 of Navbar.js.
> 
> Currently also need to log on/off in order to update props.auth to contain any newly added courses for a user. Will change so that GET is automatically called to update props.auth on course addition/creation later.

Resolved this issue with Christopher; now just waiting for the implementation of a REST api method that adds newly created assignments to its course's assignmentIds array before all frontend features are complete. See latest commit message.

2021-12-01 20:06 UTC, ChrisLouie10 requested changes

2021-12-01 20:06 UTC, ChrisLouie10 commented on client/src/actions/courseActions.js
> +  updateLocalUserData(userId)
might need to add an await here and async at the beginning of the function.

2021-12-01 20:49 UTC, merged